CREATE TABLE `pharmazing`.`users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `platform` ENUM('ios', 'android', 'unknown') DEFAULT 'unknown',
  `fcm_token` VARCHAR(200) DEFAULT '',
  `phone_id` VARCHAR(50) DEFAULT '',
  `tablet_id` VARCHAR(50) DEFAULT '',
  `phone_login` DATETIME DEFAULT '2000-01-01 00:00:00',
  `tablet_login` DATETIME DEFAULT '2000-01-01 00:00:00',
  `admin` TINYINT(1) DEFAULT false,
  `deleted` TINYINT(1) DEFAULT false,
  `lng` VARCHAR(2) DEFAULT 'de',
  `email` VARCHAR(70) DEFAULT '',
  `affiliate_code` VARCHAR(50) DEFAULT '',
  `password` VARCHAR(80) DEFAULT '',
  `name` VARCHAR(60) DEFAULT '',
  `surname` VARCHAR(60) DEFAULT '',
  `sms_confirmed` TINYINT(1) DEFAULT false,
  `email_confirmed` TINYINT(1) DEFAULT false,
  `phonenumber` VARCHAR(30) DEFAULT '',
  `country` VARCHAR(30) DEFAULT '',
  `country_device` VARCHAR(30) DEFAULT '',
  `university` VARCHAR(50) DEFAULT '',
  `occupation` VARCHAR(70) DEFAULT '',
  `city` VARCHAR(50) DEFAULT '',
  `studies` VARCHAR(70) DEFAULT 'NA',
  `trial` TINYINT(1) DEFAULT false,
  `trial_start_date_epoch` BIGINT DEFAULT 0,
  `trial_end_date` DATETIME NULL,
  `trial_end_date_epoch` BIGINT DEFAULT 0,
  `active_subscription` TINYINT(1) DEFAULT false,
  `subscription_start_date` DATETIME NULL,
  `subscription_end_date` DATETIME NULL,
  `subscription_end_date_epoch` BIGINT DEFAULT 0,
  `reset_token` VARCHAR(30) DEFAULT '',
  `reset_expiry_date` DATETIME NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));