CREATE TABLE `pharmazing`.`subscriptions` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) NULL,
  `platform` ENUM('ios', 'android', 'unknown') DEFAULT 'unknown',
  `productId` VARCHAR(30) NULL,
  `acknowledgementState` INT(1) DEFAULT 0,
  `purchaseToken` VARCHAR(150) NULL,
  `originalPurchaseTimeMillis` BIGINT NULL,
  `startTimeMillis` BIGINT NULL,
  `expiryTimeMillis` BIGINT DEFAULT 0,
  `userCancellationTimeMillis` BIGINT NULL,
  `signedDateTimeMillis` BIGINT NULL,
  `autoRenewing` TINYINT(1) DEFAULT false,
  `trial` TINYINT(1) DEFAULT false,
  `should_verify` TINYINT(1) DEFAULT true,
  `priceCurrencyCode` VARCHAR(10) NULL,
  `priceAmountMicros` INT(12) NULL,
  `countryCode` VARCHAR(20) NULL,
  `paymentState` INT(1) NULL,
  `orderId` VARCHAR(30) NULL,
  `originalOrderId` VARCHAR(30) NULL,
  `cancelReason` INT(2) NULL,
  `statusIOS` INT(1) NULL,
  `purchaseType` INT(1) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));