-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQglawB3+kAIeAESswQ
INU3X6/10ymjOCQjV02USue7ExqgCgYIKoZIzj0DAQehRANCAAT2aoAeeisrdeMm
QwtkFyatOZq0/99maHvNjfbtm3gyS0GUpdOPTgFtkLjJuTMlu5KYIsdpBgcnamwa
gCYWSCkX
-----END PRIVATE KEY-----